changelog:
  categories:
    - title: ✨ Nouveautés
      labels:
        - pr-feature
    - title: 🙌 Améliorations
      labels:
        - pr-change
    - title: 🐛 Corrections de bugs
      labels:
        - pr-bugfix
    - title: ⚠️ Modifications de l'API
      labels:
        - pr-api
    - title: 🗣 Textes & Traductions
      labels:
        - pr-i18n
    - title: 🦻 Accessibilité
      labels:
        - pr-a11y
    - title: 🧱 Build
      labels:
        - pr-build
    - title: 📄 Documentation
      labels:
        - pr-doc
    - title: 🚧 En cours de développement 🚧
      labels:
        - pr-wip

    - title: Autres
      labels:
        - pr-misc
        - "*"
