input_dir: ../../TchapX/%TARGET%/
output_dir: ../../TchapX/main/Sources/Generated/
xcassets:
  inputs:
    - ../main/Resources/CommonAssets.xcassets  
    - Resources/TargetAssets.xcassets
  outputs:
    templateName: swift5
    output: TchapAssets.swift
    params:
      enumName: TchapAsset # To not conflict with ElementX/Assets.swift
      colorTypeName: TchapColor # To not conflict with ElementX/Assets.swift
      colorAliasName: TchapAssetColorTypeAlias # To not conflict with ElementX/Assets.swift
      imageTypeName: TchapImage # To not conflict with ElementX/Assets.swift
      imageAliasName: TchapAssetImageTypeAlias # To not conflict with ElementX/Assets.swift